### ISSUE TITLE
Prayer Ending Times

### ISSUE THREAD

**Issue by Zalanshah64** [batoulapps/adhan-js#127]
My understanding of this may be flawed, so please correct me if so.

Generally, you only have so much time to pray certain prayers (Maghrib being the main one). While this library does feature support for seeing the start of prayer times, I haven't been able to find anything on the ends of prayer times. Is there a way to calculate this?

**Comment by z3bi** [comment]
The library includes sunrise time in order to know when Fajr ends. 

According to these two Hadith https://sunnah.com/bukhari:579 and https://sunnah.com/muslim:612a the ending times can be seen as follows:
- the time for dhuhr ends when its time for Asr. 
- Asr ends at sunset (Maghrib)
- Maghrib time ends at the disappearance of twilight (which is the time for Isha)
- Isha time ends at midnight
