### ISSUE TITLE
Add Awqati prayer times calculation

### ISSUE THREAD

**Issue by Merdin** [batoulapps/adhan-js#167]
‏السلام عليكم ورحمة الله وبركاته ,

I'm the owner of [awqati.org](https://awqati.org).

We are spreading our project to multiple countries and have permission of multiple scholars like the nephew of Sheikh Muhammad Nasiruddin al-Albani which is Sheikh Abdullah Adam al-Albani.

I would like our calculation method to be added, because more people are starting to use it.

I can not push my changes so this would be the code:

```
// Awqati
  Awqati() {
    return new CalculationParameters('Awqati', 9, 12);
},
```

**Comment by z3bi** [comment]
What location are these values valid for? Do you have any data to go along with these values? I don't see any additional information about it on your website. Please provide more information on how you got these values.

**Comment by z3bi** [comment]
To request a method be added to the Adhan library please provide one of the following:
- Scientific data supporting the values being used with a statement of review and support from well known scholar.
- Evidence of an official muslim organization, country, or large community using this method for their established prayer times.

Until one or both of these are provided this issue is closed. Please feel free to open a new issue once you have the above.
