### ISSUE TITLE
Sweden time calculation fails

### ISSUE THREAD

**Issue by korbav** [batoulapps/adhan-js#29]
Salam Alaikum,
I'm processing different tests on this absolutely great project and I'm facing a problem trying to calculate prayer times for Sweden (I guess it will be the same problem for all these northern geographical areas).

It would be awesome to get your input on it.
Below is the smallest snippet to reproduce :

```
const coordinates = new adhan.Coordinates(66.7222444, 17.7189);
const params = adhan.CalculationMethod.MuslimWorldLeague();
console.log(new adhan.PrayerTimes(coordinates, new Date('2020-06-21 21:55'), params));
```

The above code will output : 

```
{
     fajr: Invalid Date,
     sunrise: Invalid Date,
     dhuhr: 2020-06-21T10:52:00.000Z,
     asr: 2020-06-21T15:52:00.000Z,
     maghrib: Invalid Date,
     isha: Invalid Date
}
```

This obviously sounds problematic since several times are `Invalid`.
You can try this out here : [runkit demo](https://runkit.com/korbav/5fd5e90da08b1b001bac9d72)
Thanks!

**Comment by z3bi** [comment]
Walaikum salam,

This behavior is expected because for those coordinates there is no sunset for that day. This location is inside the arctic circle and experiences the phenomenon known as the "Midnight Sun" https://en.wikipedia.org/wiki/Midnight_sun

I would recommend checking if Maghrib or Sunrise are invalid dates. If you see invalid dates, then islamically  you could either find the nearest latitude that does have sunrise and sunset or you could find the closest date for that location that has sunrise and sunset. This is called "Aqrab balad" and "Aqrab yowm" respectively.

**Comment by korbav** [comment]
This is fascinating and that totally makes sense. 
However, instead of returning undefined times, I think we should handle that in a better way, shall I do that creating a PR with the following options? :

MidnightSunResolver:  adhan.AqrabBalad | adhan.AqrabYaum  | adhan.Unresolved

We can close this issue in any case.

**Comment by z3bi** [comment]
Thats a good idea, probably need a different name as in Winter you experience the opposite problem https://en.wikipedia.org/wiki/Polar_night

We would also want to make sure that these methods can't get stuck an infinite loop as they would technically be indeterminate.
